kind = "web"
previewPath = "/"
title = "PrepAptitude"
version = "1.0.0"
id = "artifacts/prep-aptitude"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20034

[services.development]
run = "pnpm --filter @workspace/prep-aptitude run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prep-aptitude", "run", "build" ]
publicDir = "artifacts/prep-aptitude/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20034"
BASE_PATH = "/"
